rpb-openembedded/submit_for_testing: fix DB410c template substitution
RESIZE_ROOTFS may not be defined, which results in an error
in the template substitution:
  using template: configs/rpb-openembedded/lava-job-definitions/dragonboard-410c/template-boot.yaml
  Traceback (most recent call last):
    File "configs/openembedded-lkft/submit_for_testing.py", line 258, in <module>
      main()
    File "configs/openembedded-lkft/submit_for_testing.py", line 213, in main
      lava_job = template.substitute(os.environ)
    File "/usr/lib/python2.7/string.py", line 176, in substitute
      return self.pattern.sub(convert, self.template)
    File "/usr/lib/python2.7/string.py", line 166, in convert
      val = mapping[named]
    File "/usr/lib/python2.7/UserDict.py", line 40, in __getitem__
      raise KeyError(key)
  KeyError: 'RESIZE_ROOTFS'

This exports the variable to the environment with whatever
value it had, or with blank if it had not been defined
before, but the variable is now defined.

Change-Id: Ic4adb1eb417bbb73623503a66731891ab85fe6d7
Signed-off-by: Daniel Díaz <daniel.diaz@linaro.org>