openembedded-core-upstream-master: restrict images to build
This is a new job , the intent is to make sure that OE can be used on arm64
builders/servers, but we are aware this is a new use case. For now only
core-image-minimal works with OE-core/nodistro, the others have issues:

-- core-image-lsb
ERROR: Nothing PROVIDES 'core-image-lsb'
ERROR: core-image-lsb was skipped: missing required distro feature 'pam' (not in
DISTRO_FEATURES)

-- core-image-x11
ERROR: Nothing PROVIDES 'nasm-native' (but
/home/admin/oe-core-upstream/oe-core/meta/recipes-graphics/jpeg/libjpeg-turbo_1.5.1.bb
DEPENDS on or otherwise requires it)
ERROR: nasm-native was skipped: incompatible with host aarch64-linux (not in
COMPATIBLE_HOST)
ERROR: Required build target 'core-image-x11' has no buildable providers.
Missing or unbuildable dependency chain was: ['core-image-x11',
'packagegroup-core-x11-base', 'matchbox-wm', 'libmatchbox', 'jpeg',
'nasm-native']

-- core-image-weston
ERROR: Nothing PROVIDES 'core-image-weston'
ERROR: core-image-weston was skipped: missing required distro feature 'wayland'
(not in DISTRO_FEATURES)

Change-Id: Ib63a025ef6729423de311c2bbecf98704fc02ad1
Signed-off-by: Nicolas Dechesne <nicolas.dechesne@linaro.org>