Revert "Revert "96boards-dragonboard410c-aosp-master: Disable deprecated job""
This reverts commit 37a0bc9711256cbccf4d6b78674fe8b091ce7322.

db410c32_only target build is broken in ci for sometime now,
due to following build infrastructure error, while creating
a pinned manifest:

"
AttributeError: 'NoneType' object has no attribute 'get'
++ infrastructure_error
++ echo 'Caught infrastructure error - finishing build with '\''Not Built'\'' status'
"

Disable the job since no one has complained so far. I got no
clue to fix this build job.

Signed-off-by: Amit Pundir <amit.pundir@linaro.org>
Change-Id: Iff07167305d8fe2111bc7ce3c8772c667c8963eb