android-lcr: reference-juno-m: Add missing dependency (python-parted).
Error was:
  ImportError: No module named parted

Change-Id: If3222d4c2d1f60039e18d2eb3c28d95e9e8db374
Signed-off-by: Daniel Díaz <daniel.diaz@linaro.org>