lite-aeolus: Use the very recent pip from PyPI, not just distro.
With a recent release of cmake on PyPI, we started to get errors like:

      File "/tmp/pip-build-mqtwxkay/cmake/setup.py", line 7, in <module>
        from skbuild import setup
    ImportError: No module named 'skbuild'

Search shows that this is a known issue happening due to pip being not
up to date enough.

This is initial test change, to be propagated to other Zephyr-related jobs
if successful.

Change-Id: I768a40b28654fc98b7dbc8ef803a9220d6ef3584
Signed-off-by: Paul Sokolovsky <paul.sokolovsky@linaro.org>