ci-job-configs-sanity-check: get rid of git scm plugin usage
Workaround the following error:
FATAL: org.eclipse.jgit.revwalk.RevWalk.release()V
java.lang.NoSuchMethodError: org.eclipse.jgit.revwalk.RevWalk.release()V

Caused by incompatible usage of JGit3/JGit4 in
git/git-client/gerrit-trigger plugins.

Change-Id: I7ed3a82e58a7c50a5ed97d219d6423ff552db3e7
Signed-off-by: Fathi Boudra <fathi.boudra@linaro.org>