qa-test-definitions-sanity-check: get rid of git scm plugin usage
Workaround the following error:
FATAL: org.eclipse.jgit.revwalk.RevWalk.release()V
java.lang.NoSuchMethodError: org.eclipse.jgit.revwalk.RevWalk.release()V

Caused by incompatible usage of JGit3/JGit4 in
git/git-client/gerrit-trigger plugins.

Disable the manual sanity check as the repo is obsolete.

Change-Id: Ief787dd7b4e71a8bce7674aef5dd1ed2635c0f29
Signed-off-by: Fathi Boudra <fathi.boudra@linaro.org>