lkft-aosp-master-tracking.yaml: set USE_XML_AUDIO_POLICY_CONF=1
to workaround the build error like reported here:
https://ci.linaro.org/job/lkft-aosp-master-tracking/102/console

    01:54:56 frameworks/av/services/audiopolicy/managerdefault/AudioPolicyManager.cpp:4305:2: error: Audio policy no longer supports legacy .conf configuration format
    01:54:56 #error Audio policy no longer supports legacy .conf configuration format
    01:54:56  ^
    01:54:56 1 error generated.

Change-Id: I6f53829e86662fc6e0987c7596a8321276cccb65
Signed-off-by: Yongqin Liu <yongqin.liu@linaro.org>