zephyr-upstream: Use the very recent pip from PyPI, not just distro.
With a recent release of cmake on PyPI, we started to get errors like:

      File "/tmp/pip-build-mqtwxkay/cmake/setup.py", line 7, in <module>
        from skbuild import setup
    ImportError: No module named 'skbuild'

Search shows that this is a known issue happening due to pip being not
up to date enough.

Change-Id: Id0bea0db9100e2caeff10af622eedc06c10bfd16
Signed-off-by: Paul Sokolovsky <paul.sokolovsky@linaro.org>