tcwg-abe-tested: Disable shallow-clone
In attempt to fix "git push", which complanes about:
===
To ssh://tcwg-buildslave@review.linaro.org:29418/toolchain/abe.git
 ! [rejected]        0baa492f3bc8bd0016e91bfe1afc0ad3eba52126 -> tested (non-fast-forward)
error: failed to push some refs to 'ssh://maxim.kuvyrkov@review.linaro.org:29418/toolchain/abe.git'
hint: Updates were rejected because a pushed branch tip is behind its remote
hint: counterpart. Check out this branch and integrate the remote changes
hint: (e.g. 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
===

Change-Id: Ie86aa8785c40b1994091fc2ef187b6b2ae6f4586