lava-job-definitions: ifc6410: update all the templates
LAVA has changed the schema, causing:
ValidationError: Object lacks property 'images' object_expr='object',
schema_expr='schema.properties.images.optional')

Change-Id: I9d0ea39ee11effc1cf5dababddeb8bf6d39f7abd
Signed-off-by: Fathi Boudra <fathi.boudra@linaro.org>