odp-api-check-gerrit: get rid of git scm plugin usage
Workaround the following error:
FATAL: org.eclipse.jgit.revwalk.RevWalk.release()V
java.lang.NoSuchMethodError: org.eclipse.jgit.revwalk.RevWalk.release()V

Caused by incompatible usage of JGit3/JGit4 in
git/git-client/gerrit-trigger plugins.

Fix GIT_BRANCH by using GERRIT_BRANCH, since GIT_BRANCH isn't set by the
git scm plugin anymore.

Change-Id: I87ff3fbc8fa0c85b9878f2b6c696a6f6c124803d
Signed-off-by: Fathi Boudra <fathi.boudra@linaro.org>